name: Generate LIVE EVENT M3U

on:
  schedule:
    - cron: "*/15 * * * *"
  workflow_dispatch:

jobs:
  update-live:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        # Tambahkan fetch-depth 0 agar proses pull/rebase tidak error
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Dependencies
        run: |
          pip install requests

      - name: Jalankan Script Live M3U (Auto-Match & Standby Logic)
        run: |
          cd live_event
          python generate_live.py

      - name: Commit & Push File M3U
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add live_event/live_events.m3u
          git commit -m "Auto update 🔴 LIVE & UPCOMING M3U" || echo "Tidak ada perubahan file"
          # Baris sakti untuk mencegah error "rejected"
          git pull --rebase origin main
          git push
