name: Generate LIVE EVENT M3U

on:
  schedule:
    # Berjalan otomatis setiap 30 menit
    - cron: "*/30 * * * *"
  workflow_dispatch:

jobs:
  update-live:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Dependencies
        run: |
          pip install requests

      - name: Jalankan Script Live M3U & Bantu Mapping
        run: |
          cd live_event
          python generate_live.py
          python bantu_mapping.py

      - name: Commit & Push File M3U & TXT
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add live_event/live_events.m3u live_event/DAFTAR_MAPPING.txt
          git commit -m "Auto update 🔴 LIVE SPORTS & file Mapping" || echo "Tidak ada perubahan file"
          git push
